2015-04-30 03:13:33,886  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_ASSESSMENT_DATE
java.lang.Exception: Validator.INVALID_ASSESSMENT_DATE
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.ui.UserInterface.bookAssessment(UserInterface.java:51)
	at com.infytraining.ui.UserInterface.main(UserInterface.java:19)
2015-04-30 03:13:50,812  ERROR [main] com.infytraining.business.service.TrainingServiceImpl [getAssessmentReport] - Service.NO_RECORDS_FOUND
java.lang.Exception: Service.NO_RECORDS_FOUND
	at com.infytraining.business.service.TrainingServiceImpl.getAssessmentReport(TrainingServiceImpl.java:42)
	at com.infytraining.ui.UserInterface.getAssessmentReport(UserInterface.java:61)
	at com.infytraining.ui.UserInterface.main(UserInterface.java:20)
2015-04-30 03:15:38,341  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_BATCH_NAME
java.lang.Exception: Validator.INVALID_BATCH_NAME
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.test.TrainingManagerTest.bookAssessmentInvalidBatchName(TrainingManagerTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 03:15:38,638  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_EMAIL_ID
java.lang.Exception: Validator.INVALID_EMAIL_ID
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.test.TrainingManagerTest.bookAssessmentInvalidEmailId(TrainingManagerTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 03:15:38,731  ERROR [main] com.infytraining.business.service.TrainingServiceImpl [getAssessmentReport] - Service.NO_RECORDS_FOUND
java.lang.Exception: Service.NO_RECORDS_FOUND
	at com.infytraining.business.service.TrainingServiceImpl.getAssessmentReport(TrainingServiceImpl.java:42)
	at com.infytraining.test.TrainingManagerTest.getAssessmentReportNotFound(TrainingManagerTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 03:16:00,320  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_BATCH_NAME
java.lang.Exception: Validator.INVALID_BATCH_NAME
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.test.TrainingManagerTest.bookAssessmentInvalidBatchName(TrainingManagerTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 03:16:00,398  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_EMAIL_ID
java.lang.Exception: Validator.INVALID_EMAIL_ID
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.test.TrainingManagerTest.bookAssessmentInvalidEmailId(TrainingManagerTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 03:16:00,414  ERROR [main] com.infytraining.business.service.TrainingServiceImpl [getAssessmentReport] - Service.NO_RECORDS_FOUND
java.lang.Exception: Service.NO_RECORDS_FOUND
	at com.infytraining.business.service.TrainingServiceImpl.getAssessmentReport(TrainingServiceImpl.java:42)
	at com.infytraining.test.TrainingManagerTest.getAssessmentReportNotFound(TrainingManagerTest.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:111)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:274)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:242)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:240)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:48)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:233)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:303)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)
2015-04-30 05:03:20,349  ERROR [main] com.infytraining.business.validator.Validator [validate] - Validator.INVALID_ASSESSMENT_DATE
java.lang.Exception: Validator.INVALID_ASSESSMENT_DATE
	at com.infytraining.business.validator.Validator.validate(Validator.java:30)
	at com.infytraining.business.service.TrainingServiceImpl.bookAssessment(TrainingServiceImpl.java:19)
	at com.infytraining.ui.UserInterface.bookAssessment(UserInterface.java:51)
	at com.infytraining.ui.UserInterface.main(UserInterface.java:19)
